// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_71HH9OeYteHArYbm3wJtuSC2037NCjs',
    appId: '1:418471627168:android:d9dbce8b1c37a9f7b07cc5',
    messagingSenderId: '418471627168',
    projectId: 'road-sefty-12b68',
    databaseURL: 'https://road-sefty-12b68-default-rtdb.firebaseio.com',
    storageBucket: 'road-sefty-12b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsilBnYyhO-foACfr-fJezgRObLStVHVs',
    appId: '1:418471627168:ios:2183f72b894b6a4fb07cc5',
    messagingSenderId: '418471627168',
    projectId: 'road-sefty-12b68',
    databaseURL: 'https://road-sefty-12b68-default-rtdb.firebaseio.com',
    storageBucket: 'road-sefty-12b68.appspot.com',
    androidClientId: '418471627168-djdq5nievh6c5cmkm2307mhtc9avu782.apps.googleusercontent.com',
    iosClientId: '418471627168-gd2cj9aehoou1jca8ki3aughfqvdanea.apps.googleusercontent.com',
    iosBundleId: 'com.example.geolocationApp',
  );
}
